### ISSUE TITLE
Importing `getMethods()` from the `methods` package

### ISSUE THREAD

**Issue by mmaechler** [HenrikBengtsson/R.oo#29]
You import `getMethods()` from R's own `{methods}` package:
https://github.com/HenrikBengtsson/R.oo/blob/develop/NAMESPACE#L11

I think you can safely remove that line: there's no need to import,
 as you really define your own `getMethods()` (R.oo) generic and methods.

The reason this is an issue: We (R core) want to (finally formally) deprecate `getMethods()` in the Spring 2025 release of R.
... which is *still* not an issue for you.  ... but eventually, deprecated functions become defunct and then are removed and at that point in time, you'd get a failure even during build time of R.oo

**Comment by HenrikBengtsson** [comment]
Thanks. Now fixed in the next release.

**Comment by HenrikBengtsson** [comment]
UPDATE 2024-11-01: R.oo 1.27.0 is now on CRAN.
